"""
moco_peptide_optimizer.py

MOCO-CEM style optimizer for peptide design (replacement for Simulated Annealing).

- Objective: MINIMIZE the model-predicted score (smaller is better).
- Works with your existing globals:
    AMINO_ACIDS (iterable of allowed amino acid symbols, e.g. "ACDE...")
    device      (torch device)
- Uses the same model inference logic you had (lstm/cnn/lstm_vae/encdec).

Usage (inside your generate_peptides_with_best_model):
    optimizer = MocoCEMPeptideOptimizer(
        model=model,
        model_type=model_type,
        score_mean=score_mean,
        score_std=score_std,
        batch_size=256,
        max_iterations=300,
        local_steps=30
    )
    results = optimizer.optimize(initial_peptide, n_samples=n_optimizations)

Author: generated by ChatGPT
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Dict, List, Tuple, Any, Optional

import numpy as np
import torch


@dataclass
class MocoOptions:
    # Budget
    max_iterations: int = 300
    batch_size: int = 256
    elite_frac: float = 0.12
    alpha: float = 0.18

    # Exploration -> exploitation
    tau_start: float = 1.8
    tau_end: float = 0.65
    tau_schedule: str = "linear"  # "linear" or "exp"

    # Stability
    base_mix: float = 0.05
    min_prob: float = 1e-6

    # Elite local improvement
    use_local_search: bool = True
    local_search_elite_frac: float = 0.25
    local_steps: int = 30

    # Reproducibility
    seed: int = 1


class MocoCEMPeptideOptimizer:
    """
    MOCO-CEM style optimizer for peptide design:
        theta (pos x aa logits) -> sample peptides -> select elites -> update theta.

    Minimization: smaller score is better.
    """

    def __init__(
        self,
        model: torch.nn.Module,
        model_type: str,
        score_mean: float,
        score_std: float,
        *,
        # You can pass either individual parameters or an options dataclass
        options: Optional[MocoOptions] = None,
        max_iterations: Optional[int] = None,
        batch_size: Optional[int] = None,
        elite_frac: Optional[float] = None,
        alpha: Optional[float] = None,
        tau_start: Optional[float] = None,
        tau_end: Optional[float] = None,
        tau_schedule: Optional[str] = None,
        base_mix: Optional[float] = None,
        min_prob: Optional[float] = None,
        use_local_search: Optional[bool] = None,
        local_search_elite_frac: Optional[float] = None,
        local_steps: Optional[int] = None,
        seed: Optional[int] = None,
    ):
        # ---- options ----
        if options is None:
            options = MocoOptions()

        # override via kwargs if provided
        if max_iterations is not None: options.max_iterations = int(max_iterations)
        if batch_size is not None: options.batch_size = int(batch_size)
        if elite_frac is not None: options.elite_frac = float(elite_frac)
        if alpha is not None: options.alpha = float(alpha)
        if tau_start is not None: options.tau_start = float(tau_start)
        if tau_end is not None: options.tau_end = float(tau_end)
        if tau_schedule is not None: options.tau_schedule = str(tau_schedule)
        if base_mix is not None: options.base_mix = float(base_mix)
        if min_prob is not None: options.min_prob = float(min_prob)
        if use_local_search is not None: options.use_local_search = bool(use_local_search)
        if local_search_elite_frac is not None: options.local_search_elite_frac = float(local_search_elite_frac)
        if local_steps is not None: options.local_steps = int(local_steps)
        if seed is not None: options.seed = int(seed)

        self.opts = options

        # ---- model ----
        self.model = model
        self.model_type = model_type
        self.score_mean = float(score_mean)
        self.score_std = float(score_std)

        # ---- amino acids ----
        # Expect AMINO_ACIDS to be defined in your project.
        try:
            from __main__ import AMINO_ACIDS  # common in notebooks/scripts
        except Exception:
            # If not running from __main__, try importing from a module path you might use.
            # If this fails, the user should ensure AMINO_ACIDS is available in global scope.
            AMINO_ACIDS = None

        if AMINO_ACIDS is None:
            raise RuntimeError(
                "AMINO_ACIDS is not defined. Please define AMINO_ACIDS (allowed amino acids) "
                "in your main script before creating MocoCEMPeptideOptimizer."
            )

        self.amino_acids = list(AMINO_ACIDS)
        self.A = len(self.amino_acids)
        self.L = 12  # peptide length fixed in your code

        self.aa_to_idx = {aa: i for i, aa in enumerate(self.amino_acids)}
        self.idx_to_aa = {i: aa for aa, i in self.aa_to_idx.items()}

        # ---- device ----
        try:
            from __main__ import device
        except Exception:
            device = None
        if device is None:
            raise RuntimeError(
                "device is not defined. Please define `device = torch.device(...)` "
                "in your main script before creating MocoCEMPeptideOptimizer."
            )
        self.device = device

        self.model.eval()

        random.seed(self.opts.seed)
        np.random.seed(self.opts.seed)

    # ----------------------
    # Model scoring
    # ----------------------
    def peptide_to_one_hot(self, peptide: str) -> np.ndarray:
        one_hot = np.zeros((self.L, self.A), dtype=np.float32)
        for i, aa in enumerate(peptide):
            if aa in self.aa_to_idx:
                one_hot[i, self.aa_to_idx[aa]] = 1.0
        return one_hot[np.newaxis, :, :]

    def predict_score(self, peptide: str) -> float:
        one_hot = self.peptide_to_one_hot(peptide)
        X = torch.tensor(one_hot, dtype=torch.float32).to(self.device)

        with torch.no_grad():
            if self.model_type == "lstm_vae":
                _, _, _, pred_norm = self.model(X)
            elif self.model_type == "encdec":
                _, pred_norm = self.model(X)
            else:
                pred_norm = self.model(X)

            pred = pred_norm.cpu().numpy()[0] * self.score_std + self.score_mean
            return float(pred)

    # ----------------------
    # Internal helpers
    # ----------------------
    @staticmethod
    def _softmax(x: np.ndarray) -> np.ndarray:
        x = x - np.max(x)
        e = np.exp(x)
        return e / (np.sum(e) + 1e-12)

    def _tau(self, it: int) -> float:
        K = max(1, self.opts.max_iterations)
        if K == 1:
            return max(self.opts.tau_end, 1e-6)

        if self.opts.tau_schedule.lower() == "exp":
            c = 5.0 / (K - 1)
            tau = self.opts.tau_end + (self.opts.tau_start - self.opts.tau_end) * np.exp(-c * (it - 1))
        else:
            tau = self.opts.tau_start + (self.opts.tau_end - self.opts.tau_start) * (it - 1) / (K - 1)

        return max(float(tau), 1e-6)

    def _init_theta_from_peptide(self, initial_peptide: str, boost: float = 2.0) -> np.ndarray:
        theta = np.random.randn(self.L, self.A).astype(np.float64) * 0.01
        for i, aa in enumerate(initial_peptide):
            if aa in self.aa_to_idx:
                theta[i, self.aa_to_idx[aa]] += boost
        return theta

    def _theta_to_probs(self, theta: np.ndarray) -> np.ndarray:
        P = np.zeros_like(theta, dtype=np.float64)
        for i in range(self.L):
            p = self._softmax(theta[i])
            p = np.maximum(p, self.opts.min_prob)
            p = p / np.sum(p)
            P[i] = p
        return P

    def _sample_peptide(self, theta: np.ndarray, tau: float) -> str:
        peptide_idx = []
        for pos in range(self.L):
            logits = theta[pos] / tau
            p = self._softmax(logits)
            p = np.maximum(p, self.opts.min_prob)
            p = p / np.sum(p)
            idx = np.random.choice(self.A, p=p)
            peptide_idx.append(int(idx))
        return "".join(self.idx_to_aa[i] for i in peptide_idx)

    def move_operator(self, peptide: str) -> str:
        """Neighbor generator: 75% substitution, 25% swap."""
        if random.random() < 0.75:
            pos = random.randint(0, len(peptide) - 1)
            current_aa = peptide[pos]
            possible = [aa for aa in self.amino_acids if aa != current_aa]
            new_aa = random.choice(possible)
            return peptide[:pos] + new_aa + peptide[pos + 1:]
        else:
            pos1, pos2 = random.sample(range(len(peptide)), 2)
            lst = list(peptide)
            lst[pos1], lst[pos2] = lst[pos2], lst[pos1]
            return "".join(lst)

    def _local_search(self, peptide: str, current_score: float) -> Tuple[str, float]:
        """Simple greedy hill-climb on a peptide (minimization)."""
        best_p = peptide
        best_s = current_score
        for _ in range(self.opts.local_steps):
            cand = self.move_operator(best_p)
            cs = self.predict_score(cand)
            if cs < best_s:
                best_p, best_s = cand, cs
        return best_p, best_s

    @staticmethod
    def _elite_weights_rank(m: int) -> np.ndarray:
        r = np.arange(1, m + 1, dtype=np.float64)
        w = 1.0 / r
        w /= np.sum(w)
        return w

    # ----------------------
    # Main optimization
    # ----------------------
    def optimize(self, initial_peptide: str, n_samples: int = 1) -> List[Dict[str, Any]]:
        """
        Run MOCO-CEM optimization.
        n_samples: number of independent MOCO runs (multi-start).

        Returns: list of dicts (compatible with your previous SA result format).
        """
        results: List[Dict[str, Any]] = []

        elite_count = max(1, int(round(self.opts.batch_size * self.opts.elite_frac)))
        ls_count = max(1, int(round(self.opts.batch_size * self.opts.local_search_elite_frac)))

        for sample_idx in range(n_samples):
            if sample_idx == 0:
                start_peptide = initial_peptide
            else:
                start_peptide = "".join(np.random.choice(self.amino_acids, size=self.L))

            theta = self._init_theta_from_peptide(start_peptide, boost=2.0)

            best_peptide = start_peptide
            best_score = self.predict_score(best_peptide)
            trajectory: List[Tuple[int, float]] = [(0, best_score)]

            for it in range(1, self.opts.max_iterations + 1):
                tau = self._tau(it)

                batch: List[str] = []
                scores = np.zeros(self.opts.batch_size, dtype=np.float64)

                for b in range(self.opts.batch_size):
                    p = self._sample_peptide(theta, tau)
                    s = self.predict_score(p)
                    batch.append(p)
                    scores[b] = s

                # optional local search on top candidates
                if self.opts.use_local_search:
                    ord_idx = np.argsort(scores)  # ascending (minimize)
                    top = ord_idx[:ls_count]
                    for idx in top:
                        p0 = batch[int(idx)]
                        s0 = float(scores[int(idx)])
                        p1, s1 = self._local_search(p0, s0)
                        batch[int(idx)] = p1
                        scores[int(idx)] = s1

                # update incumbent best
                min_idx = int(np.argmin(scores))
                if float(scores[min_idx]) < best_score:
                    best_score = float(scores[min_idx])
                    best_peptide = batch[min_idx]
                    trajectory.append((it, best_score))

                # elites
                ord_idx = np.argsort(scores)
                elite_idx = ord_idx[:elite_count]
                elite_peps = [batch[int(i)] for i in elite_idx]

                # rank weights (best gets largest)
                w = self._elite_weights_rank(len(elite_peps))

                freq = np.zeros((self.L, self.A), dtype=np.float64)
                for e, pep in enumerate(elite_peps):
                    we = float(w[e])
                    for pos, aa in enumerate(pep):
                        freq[pos, self.aa_to_idx[aa]] += we

                eliteP = freq / (np.sum(freq, axis=1, keepdims=True) + 1e-12)

                # base mix: keep exploration
                Pcur = self._theta_to_probs(theta)
                if self.opts.base_mix > 0:
                    eliteP = (1.0 - self.opts.base_mix) * eliteP + self.opts.base_mix * Pcur

                # EMA update in prob space
                Pnew = (1.0 - self.opts.alpha) * Pcur + self.opts.alpha * eliteP
                Pnew = np.maximum(Pnew, self.opts.min_prob)
                Pnew /= (np.sum(Pnew, axis=1, keepdims=True) + 1e-12)

                theta = np.log(Pnew + 1e-12)

            results.append({
                "best_peptide": best_peptide,
                "best_score": best_score,
                "initial_peptide": start_peptide,
                "initial_score": self.predict_score(start_peptide),
                "trajectory": trajectory,
                "improvement": self.predict_score(start_peptide) - best_score,
                "moco_opts": self.opts.__dict__.copy(),
            })

        return results
