#!/usr/bin/env python3
"""Adim 13: laboratuvara gidecek peptit ozet belgesini uretir (v2).

    python scripts/13_make_peptide_summary.py

URETILEN_PEPTIDLER_OZET.docx dosyasinin yeni hatta karsilik gelen surumu.
Her sayi results/ altindaki artefaktlardan okunur; belgede elle yazilmis
tek bir deger yoktur.

v1'den yapisal farklar ve nedenleri
-----------------------------------
* "Baslangic Peptid / Bas. Skor / Iyilestirme" sutunlari YOK. Yeni uretim
  hatti baslangic dizisini kaydetmiyor; uydurmak yerine cikarildi.
* Cesitlilik orani tahmin degil olculen deger (uretim ciktisindaki
  diversity_ratio).
* Skor sutunu, uretimde kullanilan vekil modelin (encoder-decoder,
  kimlik-duyarli bolme) tahminidir; en iyi TAHMINCI olan CNN'den farklidir
  ve bu belgede ikisi ayri ayri verilir.
"""
import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pbp.exit import clean_exit
from pbp.config import load_config

METHODS = ["SA", "ILS", "MOCO-CEM"]
TR = {"SA": "Simulated Annealing (SA)", "ILS": "Iterated Local Search (ILS)",
      "MOCO-CEM": "MOCO-CEM"}


def load(out: Path, cfg):
    arch = json.loads((out / "analysis" / "generator_comparison.json")
                      .read_text(encoding="utf-8"))["selection"]["selected"]
    gen = {p: json.loads((out / "generated" / f"{p}_{arch}_clustered.json")
                         .read_text(encoding="utf-8")) for p in cfg["plastics"]}
    summ = json.loads((out / "summary_clustered.json").read_text(encoding="utf-8"))
    r2 = {(r["plastic"], r["architecture"]): r for r in summ}
    nov = {r["plastic"]: r for r in
           json.loads((out / "analysis" / "novelty.json").read_text(encoding="utf-8"))}
    sel = json.loads((out / "analysis" / "selectivity.json").read_text(encoding="utf-8"))
    ivraw = json.loads(
        (out / "analysis" / "independent_validation.json").read_text(encoding="utf-8"))
    iv = {r["plastic"]: r for r in ivraw}
    # Peptit bazinda: optimizasyonda kullanilmayan modelin skoru
    val = {(r["plastic"], x["sequence"]): x for r in ivraw for x in r["sequences"]}
    import csv as _csv
    with (out / "analysis" / "selectivity_per_peptide.csv").open(encoding="utf-8") as fh:
        per_pep = {(r["optimized_for"], r["sequence"]): r for r in _csv.DictReader(fh)}
    return arch, gen, r2, nov, sel, iv, val, per_pep


def main() -> int:
    import docx
    from docx.shared import Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    cfg = load_config()
    out = Path(cfg["out_dir"])
    P = list(cfg["plastics"])
    arch, gen, r2, nov, sel, iv, val, per_pep = load(out, cfg)

    d = docx.Document()
    cp = d.core_properties
    cp.author = "Sahin Atakan Emre"
    cp.last_modified_by = "Sahin Atakan Emre"
    cp.title = "Uretilen Peptidler - Ozet (v2)"
    cp.comments = ""        # varsayilan "generated by python-docx" notunu temizler
    cp.revision = 1
    st = d.styles["Normal"]
    st.font.name = "Calibri"
    st.font.size = Pt(10.5)
    for s in d.sections:
        s.left_margin = s.right_margin = Cm(2.0)
        s.top_margin = s.bottom_margin = Cm(2.0)

    def h(text, level=1):
        p = d.add_heading(text, level=level)
        for r in p.runs:
            r.font.name = "Calibri"
        return p

    def para(text="", bold=False, italic=False, size=10.5, after=6):
        p = d.add_paragraph()
        r = p.add_run(text)
        r.bold, r.italic = bold, italic
        r.font.size = Pt(size)
        p.paragraph_format.space_after = Pt(after)
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        return p

    def table(rows, widths=None, size=9):
        t = d.add_table(rows=len(rows), cols=len(rows[0]))
        t.style = "Table Grid"
        for i, row in enumerate(rows):
            for j, cell in enumerate(row):
                c = t.cell(i, j)
                c.text = ""
                pp = c.paragraphs[0]
                rr = pp.add_run(str(cell))
                rr.font.size = Pt(size)
                rr.font.name = "Calibri"
                rr.bold = (i == 0)
                pp.paragraph_format.space_after = Pt(0)
        d.add_paragraph().paragraph_format.space_after = Pt(8)
        return t

    # ---------------------------------------------------------------- baslik
    h("Uretilen Peptidler — Optimizasyon Yontemlerine Gore Ozet (v2)", 0)
    total = sum(len(v["runs"]) for g in gen.values() for v in g.values())
    uniq = len({r["sequence"] for g in gen.values() for v in g.values()
                for r in v["runs"]})
    para(f"Olusturulma tarihi: {date.today().strftime('%d.%m.%Y')}", bold=True, after=0)
    para(f"Plastik tipi: {len(P)} ({', '.join(P)})", bold=True, after=0)
    para(f"Toplam peptit: {total} ({total // len(P)} x {len(P)} plastik) — "
         f"{uniq} benzersiz dizi", bold=True, after=0)
    para(f"Uretimde kullanilan vekil model: {arch} (encoder-decoder), "
         f"kimlik-duyarli (identity-aware) bolme", bold=True, after=12)

    # ------------------------------------------------- v1'den farklar (onemli)
    h("0. Onceki listeden farklar — lutfen once bunu okuyun", 1)
    para("Bu liste, daha once docking icin gonderilen listenin yerine gecer. "
         "Calisma hakem revizyonu sirasinda bastan calistirildi: veri bolme "
         "yontemi degisti, modeller yeniden egitildi ve peptitler yeniden "
         "uretildi. Sonuc olarak:")
    table([
        ["Konu", "Onceki liste", "Bu liste (v2)"],
        ["Peptit dizileri",
         "Eski hattan uretilen diziler",
         "TAMAMEN FARKLI. Onceki listenin en iyi 6 peptidinden hicbiri bu "
         "listede yok. Eski diziler icin yapilan docking sonuclari bu "
         "calismaya ait degildir."],
        ["Benzersizlik",
         "Ayni dizi bir tabloda birden cok kez tekrar edebiliyordu",
         f"{uniq}/{total} dizi benzersiz; tekrar yok"],
        ["Skorun kaynagi",
         "Rastgele bolmeyle egitilmis model",
         "Kimlik-duyarli bolmeyle egitilmis encoder-decoder modeli"],
        ["Baslangic peptidi",
         "Tabloda veriliyordu (uc yontemde de ayni 10 sabit dizi)",
         "Yeni hatta her kosu kendi rastgele baslangicini cekiyor ve bu "
         "kaydedilmiyor; ayrica MOCO-CEM dagilimdan basladigi icin tek bir "
         "baslangic peptidi KAVRAMSAL OLARAK yoktur. Sutun cikarildi."],
        ["Iyilestirme",
         "Uretilen skor eksi o kosunun rastgele baslangic skoru",
         "Uretilen skor eksi o plastigin rastgele 12-mer ORTALAMASI "
         "(2.000 dizi). Ortak ve sabit bir referans oldugu icin peptitler "
         "ve yontemler arasinda karsilastirilabilir; eski tanim ise "
         "baslangicin ne kadar kotu rastladigina bagliydi."],
    ])
    para("Docking yapilacaksa bu listedeki dizilerle yapilmalidir.", bold=True)

    # ------------------------------------------------------- genel performans
    h("1. Genel performans ozeti", 1)
    rows = [["Plastik", "SA en iyi", "ILS en iyi", "MOCO-CEM en iyi",
             "Test R² (uretici, encdec)", "Test R² (en iyi tahminci, CNN)"]]
    for p in P:
        rows.append([p] + [f"{gen[p][m]['best']['score']:.2f}" for m in METHODS]
                    + [f"{r2[(p, arch)]['test_r2_mean']:.4f}",
                       f"{r2[(p, 'cnn')]['test_r2_mean']:.4f}"])
    table(rows)
    para("Skor ne kadar negatifse tahmin edilen baglanma o kadar gucludur. "
         "Iki R² sutunu ayri verilmistir: peptitler encoder-decoder modeliyle "
         "uretilmistir (optimizasyona daha dayanikli oldugu icin secilmistir), "
         "en yuksek tahmin dogrulugu ise CNN'dedir.", italic=True, size=9)

    # --------------------------------------------------- yontem bazli tablolar
    for si, m in enumerate(METHODS, start=2):
        h(f"{si}. {TR[m]} peptitleri", 1)
        for p in P:
            h(f"{si}.{P.index(p) + 1} {p} — {m}", 2)
            runs = sorted(gen[p][m]["runs"], key=lambda r: r["score"])
            base = iv[p]["random_baseline"]["mean"]
            rows = [["#", "Uretilen peptit", "Uretici model skoru",
                     "Bagimsiz model skoru", "Rastgele temele gore kazanc",
                     "Secicilik indeksi", "Hedefinde en iyi mi"]]
            for i, r in enumerate(runs, 1):
                v = val.get((p, r["sequence"]))
                pp = per_pep.get((p, r["sequence"]))
                rows.append([
                    i, r["sequence"], f"{r['score']:.2f}",
                    f"{v['validator_score']:.2f}" if v else "-",
                    f"+{base - r['score']:.2f}",
                    f"{float(pp['selectivity_index']):+.1f}" if pp else "-",
                    ("evet" if pp and pp["best_scoring_plastic"] == p
                     else ("HAYIR -> " + pp["best_scoring_plastic"] if pp else "-")),
                ])
            table(rows, size=8.5)
            rmse = r2[(p, arch)]["test_rmse_mean"]
            para(f"Uretici modelin test RMSE'si {rmse:.2f}; bu listedeki skorlar "
                 f"OLCUM DEGIL TAHMINDIR ve bu buyuklukteki farklar anlamli "
                 f"sayilmamalidir. Bagimsiz model skoru, optimizasyonda ve "
                 f"model seciminde hic kullanilmayan "
                 f"{iv[p]['validator_model']['architecture'].upper()} modelinden "
                 f"gelir; optimizasyonun vekil modeli somurup somurmedigini "
                 f"peptit bazinda gosterir. Rastgele 12-mer temeli "
                 f"({iv[p]['random_baseline']['n']:,} dizi): {base:.2f}.",
                 italic=True, size=8.5)

    # ----------------------------------------------------- yontem kiyaslamasi
    h("5. Yontem karsilastirmasi", 1)
    h("5.1 Plastik basina en iyi peptit", 2)
    rows = [["Plastik", "En iyi peptit", "Skor", "Yontem",
             "Egitim setine en yakin komsu kimligi"]]
    best_overall = {}
    for p in P:
        b = min(((gen[p][m]["best"], m) for m in METHODS), key=lambda x: x[0]["score"])
        best_overall[p] = b
        rows.append([p, b[0]["sequence"], f"{b[0]['score']:.2f}", b[1],
                     f"%{nov[p]['nn_identity_mean_pct']:.1f} (ortalama)"])
    table(rows)

    h("5.2 Yontem bazinda ortalama performans", 2)
    rows = [["Yontem", "Ort. en iyi skor", "Ort. skor (30 peptit)",
             "En iyi plastik", "En zayif plastik"]]
    for m in METHODS:
        bs = {p: gen[p][m]["best"]["score"] for p in P}
        ms = [gen[p][m]["mean_score"] for p in P]
        lo = min(bs, key=bs.get)
        hi = max(bs, key=bs.get)
        rows.append([TR[m], f"{sum(bs.values()) / len(bs):.2f}",
                     f"{sum(ms) / len(ms):.2f}",
                     f"{lo} ({bs[lo]:.2f})", f"{hi} ({bs[hi]:.2f})"])
    table(rows)

    h("5.3 Hesaplama butcesi", 2)
    rows = [["Yontem", "Kosu basina ortalama degerlendirme", "SA'ya gore"]]
    budgets = {}
    for m in METHODS:
        ev = [r["n_evaluations"] for p in P for r in gen[p][m]["runs"]]
        budgets[m] = sum(ev) / len(ev)
    for m in METHODS:
        rows.append([TR[m], f"{budgets[m]:,.0f}",
                     f"{budgets[m] / budgets['SA']:.1f}x"])
    table(rows)
    para("Yontemler farkli degerlendirme butceleriyle calismaktadir. SA, "
         f"kosu basina {budgets['SA']:,.0f} degerlendirme ile en dusuk butceyi "
         "kullanirken en iyi ortalama skoru elde etmektedir. Degerlendirme "
         "sayisi kosunun hesaplama maliyetidir; peptit tablolarinda yer "
         "almaz.", size=9)

    h("5.4 Cesitlilik analizi", 2)
    rows = [["Yontem", "Benzersiz peptit orani", "Aciklama"]]
    for m in METHODS:
        dr = [gen[p][m]["diversity_ratio"] for p in P]
        avg = sum(dr) / len(dr)
        rows.append([TR[m], f"%{100 * avg:.0f}",
                     "Olculen deger; her calismada uretilen 10 peptidin "
                     "benzersiz olani"])
    table(rows)
    para("Onceki listede bu oranlar tahminiydi ve MOCO-CEM icin %40 olarak "
         "veriliyordu. Yeni hatta uc yontem de tekrarsiz dizi uretmektedir.",
         italic=True, size=9)

    # -------------------------------------------------------------- motifler
    h("6. Peptit bazinda secicilik", 1)
    fails = [(p, seq, r) for (p, seq), r in per_pep.items()
             if r["best_scoring_plastic"] != p]
    by_p = {p: sum(1 for f in fails if f[0] == p) for p in P}
    para(f"Peptit setleri kendi hedeflerinde en iyi skoru almaktadir "
         f"({sel['summary']['n_target_best']}/{sel['summary']['n_targets']} plastik). "
         f"Peptit bazinda ise diziler arasinda hedef tercihi degisebilmektedir; "
         f"docking icin aday secerken bu bilgi kullanilmistir.")
    rows = [["Plastik", "Hedefinde en iyi skorlayan peptit"]]
    for p in P:
        rows.append([p, f"{30 - by_p[p]}/30"])
    table(rows)
    para("Docking listesine (bolum 8) yalnizca kendi hedefinde en iyi "
         "skorlayan tasarimlar alinmistir.", size=9)

    h("7. Amino asit motif analizi", 1)
    allseq = {p: [r["sequence"] for v in gen[p].values() for r in v["runs"]] for p in P}

    def motifs(idx):
        c = Counter()
        where = {}
        for p, seqs in allseq.items():
            for s in seqs:
                mo = s[:2] if idx == 0 else s[-2:]
                c[mo] += 1
                where.setdefault(mo, set()).add(p)
        return c, where

    for title, idx in (("7.1 En sik gorulen baslangic motifleri", 0),
                       ("7.2 En sik gorulen bitis motifleri", 1)):
        h(title, 2)
        c, where = motifs(idx)
        rows = [["Motif", "Frekans", "Gorüldügü plastikler"]]
        for mo, n in c.most_common(5):
            rows.append([mo, f"%{100 * n / total:.1f} ({n}/{total})",
                         ", ".join(sorted(where[mo]))])
        table(rows)

    # ------------------------------------------------------- docking listesi
    h("8. Docking icin onerilen liste", 1)
    sel_csv = out / "analysis" / "docking_selection.csv"
    if sel_csv.exists():
        import csv as _csv
        with sel_csv.open(encoding="utf-8") as fh:
            dock = list(_csv.DictReader(fh))
        n_per = len(dock) // len(P)
        para(f"Docking, hakem talebi geregi ML skoruyla KORELE edilecektir. "
             f"Bu korelasyonun anlamli olmasi icin docking'e sokulan kumenin "
             f"genis bir tahmin araligina yayilmasi gerekir; yalnizca en iyi "
             f"peptitler secilirse skorlar dar bir bantta toplanir ve katsayi "
             f"yorumlanamaz. Bu nedenle plastik basina {n_per} peptitlik "
             f"katmanli bir kume secilmistir ({len(dock)} peptit).")
        rows = [["Grup", "Rolu"],
                ["designed", "Yeni uretilen peptitler, uretilen skor araligini tarar"],
                ["training", "Egitim setinden, OLCULMUS baglanma skoru bilinen "
                             "diziler; docking'i tahmine degil olcume karsi "
                             "dogrulama imkani verir"],
                ["random control", "Rastgele 12-mer: araligin zayif ucu ve "
                                   "negatif kontrol"]]
        table(rows)
        for p in P:
            h(f"8.{P.index(p) + 1} {p}", 2)
            rows = [["#", "Peptit", "Grup", "Tahmin skoru", "Olculen skor"]]
            for i, r in enumerate([x for x in dock if x["plastic"] == p], 1):
                rows.append([i, r["sequence"], r["group"],
                             f"{float(r['predicted_score']):.2f}",
                             r["measured_score"] or "—"])
            table(rows)
        para("Laboratuvara: docking_selection.csv dosyasindaki docking_score, "
             "oligomer_length, n_runs, software ve notes sutunlarini "
             "doldurmaniz yeterlidir. Skoru kcal/mol cinsinden, calismanin en "
             "iyi (en negatif) baglanma enerjisi olarak veriniz ve bir plastik "
             "icinde oligomer uzunlugunu sabit tutunuz.", bold=True)
    else:
        para("docking_selection.csv bulunamadi; once "
             "scripts/12_select_docking_set.py calistirilmalidir.", italic=True)

    # ------------------------------------------------------------------- not
    h("Kaynak", 1)
    para("Bu belge results/ altindaki pipeline ciktilarindan "
         "scripts/13_make_peptide_summary.py ile otomatik uretilmistir. "
         "Icindeki hicbir sayi elle yazilmamistir.", italic=True, size=9)

    dest = Path(cfg.get("summary_doc_dir", Path(__file__).resolve().parents[2]))
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / "URETILEN_PEPTIDLER_OZET_v2.docx"
    d.save(path)
    print(f"  {path}")
    print(f"  {total} peptit, {uniq} benzersiz, {len(P)} plastik, {len(METHODS)} yontem")
    return 0


if __name__ == "__main__":
    clean_exit(main())
